spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: starwars-db
      auto-index-creation: true
server:
  port: 8080
  compression:
    #Enable response compression
    enabled: true
    #Compress the response only if the response size is ate least 1kb
    min-response-size: 1024 # compress only response
    #The comma-separeted list the mime type that should be compressed
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
